title: Next.js back-end developer exercise
description: Sample exercise for onboarding new back-end developers in Next.js 16 & TypeScript
show_downloads: true
google_analytics: 
theme: jekyll-theme-cayman
